// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import * as vscode from 'vscode';
import { CreationCapability, FabricItemMetadata } from './definitions';

// The other icons are themed by adding 'fill="white"' into the .svg files
export const fabricItemMetadata: Partial<Record<string, FabricItemMetadata>> = {
    /* eslint-disable @typescript-eslint/naming-convention*/
    'AppBackend': {
        creationCapability: CreationCapability.preview,
        creationDescription: vscode.l10n.t('Build and host backend applications and APIs powered by Fabric.'),
        displayName: vscode.l10n.t('App'),
        displayNamePlural: vscode.l10n.t('Apps'),
        iconInformation: { fileName: 'app_backend_32.svg', isThemed: false },
        portalFolder: 'appbackends',
    },
    'CopyJob': {
        creationCapability: CreationCapability.supported,
        creationDescription: vscode.l10n.t('Makes it easy to copy data in Fabric. Includes full copy, incremental copy, and event-based copy modes.'),
        displayName: vscode.l10n.t('Copy job'),
        displayNamePlural: vscode.l10n.t('Copy jobs'),
        portalFolder: 'copyjobs',
        supportsArtifactWithDefinition: true,
    },
    'CosmosDBDatabase': {
        creationCapability: CreationCapability.supported,
        creationDescription: vscode.l10n.t('Define, query and update data.'),
        displayName: vscode.l10n.t('Cosmos DB database'),
        displayNamePlural: vscode.l10n.t('Cosmos DB databases'),
        portalFolder: 'cosmosdbdatabases',
        extensionId: 'ms-azuretools.vscode-cosmosdb',
        iconInformation: { fileName: 'cosmosdb_64.svg', isThemed: true },
    },
    'Dashboard': {
        creationCapability: CreationCapability.unsupported,
        displayName: vscode.l10n.t('Dashboard'),
        displayNamePlural: vscode.l10n.t('Dashboards'),
        iconInformation: { fileName: 'dashboard_24.svg', isThemed: true },
        portalFolder: 'dashboards',
    },
    'DataPipeline': {
        creationCapability: CreationCapability.supported,
        creationDescription: vscode.l10n.t('Ingest data at scale and schedule data workflows.'),
        displayName: vscode.l10n.t('Data pipeline'),
        displayNamePlural: vscode.l10n.t('Data pipelines'),
        iconInformation: { fileName: 'pipeline_24.svg', isThemed: true },
        portalFolder: 'pipelines',
        supportsArtifactWithDefinition: true,
    },
    'Dataflow': {
        creationCapability: CreationCapability.supported,
        creationDescription: vscode.l10n.t('Prep, clean, and transform data.'),
        displayName: vscode.l10n.t('Dataflow Gen2'),
        displayNamePlural: vscode.l10n.t('Dataflows Gen2'),
        portalFolder: 'dataflows-gen2',
        supportsArtifactWithDefinition: true,
    },
    'Datamart': {
        creationCapability: CreationCapability.unsupported,
        displayName: vscode.l10n.t('Datamart'),
        displayNamePlural: vscode.l10n.t('Datamarts'),
        iconInformation: { fileName: 'datamart_24.svg', isThemed: true },
        portalFolder: 'datamarts',
    },
    'Environment': {
        creationCapability: CreationCapability.supported,
        creationDescription: vscode.l10n.t('Set up shared libraries, Spark compute settings, and resources for notebooks and Spark job definitions.'),
        displayName: vscode.l10n.t('Environment'),
        displayNamePlural: vscode.l10n.t('Environments'),
        iconInformation: { fileName: 'environment_24.svg', isThemed: true },
        portalFolder: 'sparkenvironments',
        supportsArtifactWithDefinition: true,
    },
    'Eventhouse': {
        creationCapability: CreationCapability.supported,
        creationDescription: vscode.l10n.t('Rapidly load structured, unstructured and streaming data for querying.'),
        displayName: vscode.l10n.t('Eventhouse'),
        displayNamePlural: vscode.l10n.t('Eventhouses'),
        iconInformation: { fileName: 'event_house_32.svg', isThemed: true },
        portalFolder: 'eventhouses',
        supportsArtifactWithDefinition: true,
    },
    'Eventstream': {
        creationCapability: CreationCapability.supported,
        creationDescription: vscode.l10n.t('Capture, transform, and route real-time event stream to various destinations in desired format with no-code experience.'),
        displayName: vscode.l10n.t('Eventstream'),
        displayNamePlural: vscode.l10n.t('Eventstreams'),
        iconInformation: { fileName: 'eventstream_24.svg', isThemed: true },
        portalFolder: 'eventstreams',
        supportsArtifactWithDefinition: true,
    },
    'GraphQLApi': {
        creationCapability: CreationCapability.supported,
        creationDescription: vscode.l10n.t('Create an API for GraphQL to easily connect your applications to Fabric data sources.'),
        displayName: vscode.l10n.t('API for GraphQL'),
        displayNamePlural: vscode.l10n.t('GraphQL API'),
        iconInformation: { fileName: 'graph_ql_32.svg', isThemed: true },
        portalFolder: 'graphql',
        supportsArtifactWithDefinition: true,
    },
    'KQLDashboard': {
        creationCapability: CreationCapability.supported,
        creationDescription: vscode.l10n.t('Visualize key insights to share with your team.'),
        displayName: vscode.l10n.t('Real-Time Dashboard'),
        displayNamePlural: vscode.l10n.t('Real-Time Dashboards'),
        iconInformation: { fileName: 'real_time_dashboard_24.svg', isThemed: true },
        portalFolder: 'kustodashboards',
        supportsArtifactWithDefinition: true,
    },
    'KQLDatabase': {
        creationCapability: CreationCapability.supported,
        creationDescription: vscode.l10n.t('Rapidly load structured, unstructured, and streaming data for querying.'),
        displayName: vscode.l10n.t('KQL Database'),
        displayNamePlural: vscode.l10n.t('KQL Databases'),
        iconInformation: { fileName: 'kql_database_24.svg', isThemed: true },
        portalFolder: 'databases',
        supportsArtifactWithDefinition: true,
    },
    'KQLQueryset': {
        creationCapability: CreationCapability.supported,
        creationDescription: vscode.l10n.t('Run queries on your data to produce shareable tables and visuals.'),
        displayName: vscode.l10n.t('KQL Queryset'),
        displayNamePlural: vscode.l10n.t('KQL Querysets'),
        iconInformation: { fileName: 'kql_queryset_24.svg', isThemed: true },
        portalFolder: 'queryworkbenches',
        supportsArtifactWithDefinition: true,
    },
    'Lakehouse': {
        creationCapability: CreationCapability.supported,
        creationDescription: vscode.l10n.t('Store big data for cleaning, querying, reporting, and sharing.'),
        displayName: vscode.l10n.t('Lakehouse'),
        displayNamePlural: vscode.l10n.t('Lakehouses'),
        iconInformation: { fileName: 'lakehouse_24.svg', isThemed: true },
        portalFolder: 'lakehouses',
        supportsArtifactWithDefinition: true,
    },
    'MLExperiment': {
        creationCapability: CreationCapability.supported,
        creationDescription: vscode.l10n.t('Create, run, and track development of multiple models for validating hypotheses.'),
        displayName: vscode.l10n.t('Experiment'),
        displayNamePlural: vscode.l10n.t('Experiments'),
        iconInformation: { fileName: 'experiments_24.svg', isThemed: true },
        portalFolder: 'mlexperiments',
        supportsArtifactWithDefinition: true,
    },
    'MLModel': {
        creationCapability: CreationCapability.supported,
        creationDescription: vscode.l10n.t('Use machine learning models to predict outcomes and detect anomalies in data.'),
        displayName: vscode.l10n.t('ML model'),
        displayNamePlural: vscode.l10n.t('ML models'),
        iconInformation: { fileName: 'model_24.svg', isThemed: true },
        portalFolder: 'mlmodels',
        supportsArtifactWithDefinition: true,
    },
    'MirroredDatabase': {
        creationCapability: CreationCapability.unsupported,
    },
    'MirroredWarehouse': {
        creationCapability: CreationCapability.unsupported,
        displayName: vscode.l10n.t('SQL analytics endpoint'),
        displayNamePlural: vscode.l10n.t('SQL analytics endpoints'),
        iconInformation: { fileName: 'data_warehouse_24.svg', isThemed: true },
        portalFolder: 'mountedwarehouses',
    },
    'MountedDataFactory': {
        creationCapability: CreationCapability.unsupported,
        displayName: vscode.l10n.t('Azure Data Factory'),
        displayNamePlural: vscode.l10n.t('Azure Data Factories'),
        portalFolder: 'mounteddatafactories',
        supportsArtifactWithDefinition: true,
    },
    'Notebook': {
        creationCapability: CreationCapability.supported,
        creationDescription: vscode.l10n.t('Explore, analyze, and visualize data and build ML models. Supports Apache Spark, Python, T-SQL, and more.'),
        displayName: vscode.l10n.t('Notebook'),
        displayNamePlural: vscode.l10n.t('Notebooks'),
        iconInformation: { fileName: 'notebook_24.svg', isThemed: true },
        portalFolder: 'synapsenotebooks',
        supportsArtifactWithDefinition: true,
    },
    'PaginatedReport': {
        creationCapability: CreationCapability.unsupported,
        displayName: vscode.l10n.t('Paginated Report'),
        displayNamePlural: vscode.l10n.t('Paginated Reports'),
        iconInformation: { fileName: 'paginated_report_24.svg', isThemed: true },
        portalFolder: 'rdlreports',
    },
    'Reflex': {
        creationCapability: CreationCapability.supported,
        creationDescription: vscode.l10n.t('Monitor datasets, queries, and event streams for patterns to trigger actions and alerts.'),
        displayName: vscode.l10n.t('Activator'),
        displayNamePlural: vscode.l10n.t('Activators'),
        iconInformation: { fileName: 'reflex_24.svg', isThemed: true },
        portalFolder: 'reflexes',
        supportsArtifactWithDefinition: true,
    },
    'Report': {
        displayName: vscode.l10n.t('Report'),
        displayNamePlural: vscode.l10n.t('Reports'),
        iconInformation: { fileName: 'report_24.svg', isThemed: true },
        portalFolder: 'reports',
        supportsArtifactWithDefinition: true,
    },
    'SQLDatabase': {
        creationCapability: CreationCapability.preview,
        creationDescription: vscode.l10n.t('Build modern cloud apps that scale on an intelligent, fully managed database.'),
        displayName: vscode.l10n.t('SQL database'),
        displayNamePlural: vscode.l10n.t('SQL databases'),
        iconInformation: { fileName: 'sql_database_24.svg', isThemed: true },
        portalFolder: 'sqldatabases',
    },
    'SQLEndpoint': {
        creationCapability: CreationCapability.unsupported,
        displayName: vscode.l10n.t('SQL analytics endpoint'),
        displayNamePlural: vscode.l10n.t('SQL analytics endpoints'),
        iconInformation: { fileName: 'data_warehouse_24.svg', isThemed: true },
        portalFolder: 'lakewarehouses',
    },
    'SemanticModel': {
        creationCapability: CreationCapability.unsupported,
        displayName: vscode.l10n.t('Semantic model'),
        displayNamePlural: vscode.l10n.t('Semantic models'),
        iconInformation: { fileName: 'semantic_model_32.svg', isThemed: true },
        portalFolder: 'datasets',
        supportsArtifactWithDefinition: true,
        extensionId: 'analysis-services.TMDL',
        webExtensionEnabled: true,
    },
    'SparkJobDefinition': {
        creationCapability: CreationCapability.supported,
        creationDescription: vscode.l10n.t('Define, schedule, and manage your Apache Spark jobs for big data processing.'),
        displayName: vscode.l10n.t('Spark Job Definition'),
        displayNamePlural: vscode.l10n.t('Spark Job Definitions'),
        iconInformation: { fileName: 'spark_job_definition_24.svg', isThemed: true },
        portalFolder: 'sparkjobdefinitions',
        supportsArtifactWithDefinition: true,
    },
    'UserDataFunction': {
        creationCapability: CreationCapability.supported,
        creationDescription: vscode.l10n.t('Author, host, and manage serverless user data functions optimized for Fabric.'),
        displayName: vscode.l10n.t('User data functions'),
        displayNamePlural: vscode.l10n.t('User data functions'),
        extensionId: 'fabric.vscode-fabric-functions',
        iconInformation: { fileName: 'function_set_32.svg', isThemed: true },
        portalFolder: 'userdatafunctions',
        supportsArtifactWithDefinition: true,
    },
    'VariableLibrary': {
        creationCapability: CreationCapability.supported,
        creationDescription: vscode.l10n.t('Create item variables that can be referenced across this workspace.'),
        displayName: vscode.l10n.t('Variable library'),
        displayNamePlural: vscode.l10n.t('Variable libraries'),
        portalFolder: 'variable-libraries',
        supportsArtifactWithDefinition: true,
    },
    'Warehouse': {
        creationCapability: CreationCapability.supported,
        creationDescription: vscode.l10n.t('Provide strategic insights from multiple sources into your entire business.'),
        displayName: vscode.l10n.t('Warehouse'),
        displayNamePlural: vscode.l10n.t('Warehouses'),
        iconInformation: { fileName: 'data_warehouse_24.svg', isThemed: true },
        portalFolder: 'warehouses',
    },

    // Creatable through portal, non-Preview items
    'ApacheAirflowJob': {
        displayName: vscode.l10n.t('Apache Airflow job'),
        displayNamePlural: vscode.l10n.t('Apache Airflow jobs'),
        portalFolder: 'apacheairflowprojects',
    },
    'Healthcaredatasolution': {
        displayName: vscode.l10n.t('Healthcare data solutions'),
        displayNamePlural: vscode.l10n.t('Healthcare data solutions'),
        portalFolder: 'health-data-manager',
    },
    'RetailDataManager': {
        displayName: vscode.l10n.t('Retail solutions'),
        displayNamePlural: vscode.l10n.t('Retail solutions'),
        iconInformation: { fileName: 'retail_data_manager_24.svg', isThemed: true },
        portalFolder: 'retail-data-manager',
    },
    'SustainabilityDataSolution': {
        displayName: vscode.l10n.t('Sustainability solutions'),
        displayNamePlural: vscode.l10n.t('Sustainability solutions'),
        portalFolder: 'sustainability-data-manager',
    },

    // Preview items
    'DataAgent': {
        displayName: vscode.l10n.t('Data agent'),
        displayNamePlural: vscode.l10n.t('Data agents'),
        iconInformation: { fileName: 'ai_skill_24.svg', isThemed: true },
        portalFolder: 'aiskills',
    },
    'DataverseMirror': { // Listed but unable to create in portal
    },
    'DigitalTwinBuilder': { // Listed but unable to create in portal
    },
    'Exploration': {
        displayName: vscode.l10n.t('Exploration'),
        displayNamePlural: vscode.l10n.t('Explorations'),
        iconInformation: { fileName: 'exploration_24.svg', isThemed: true },
        portalFolder: 'explorations',
    },
    'MetricSet': {
        displayName: vscode.l10n.t('Metric set'),
        displayNamePlural: vscode.l10n.t('Metric sets'),
        portalFolder: 'metricsets',
    },
    'OrgApp': {
        displayName: vscode.l10n.t('Org app'),
        displayNamePlural: vscode.l10n.t('Org apps'),
        iconInformation: { fileName: 'apps_24.svg', isThemed: true },
        portalFolder: 'orgapps',
    },

    // Obsolete?
    'AISkill': {
        displayName: vscode.l10n.t('AI Skill'),
        displayNamePlural: vscode.l10n.t('AI Skills'),
        iconInformation: { fileName: 'ai_skill_24.svg', isThemed: true },
        portalFolder: 'aiskills',
    },
    'ApacheAirflowProject': {
        displayName: vscode.l10n.t('Apache Airflow project (Preview)'),
        displayNamePlural: vscode.l10n.t('Apache Airflow projects'),
    },
    'AppFrontEnd': {
        displayName: vscode.l10n.t('AppFrontEnd'),
        displayNamePlural: vscode.l10n.t('AppFrontEnds'),
        iconInformation: { fileName: 'sql_database_24.svg', isThemed: true },
    },
    'DigitalOperation': {
        displayName: vscode.l10n.t('PAL'),
        displayNamePlural: vscode.l10n.t('PALs'),
    },
    'ExternalFunctions': {
        displayName: vscode.l10n.t('Trident Function'),
        displayNamePlural: vscode.l10n.t('Trident Functions'),
        iconInformation: { fileName: 'sql_database_24.svg', isThemed: true },
    },
    'HLSCohort': {
        displayName: vscode.l10n.t('Cohort Builder'),
        displayNamePlural: vscode.l10n.t('Cohort Builders'),
        iconInformation: { fileName: 'cohort_32.svg', isThemed: true },
        portalFolder: 'hlscohorts',
    },
    'HealthDataManager': {
        displayName: vscode.l10n.t('Healthcare solution (Preview)'),
        displayNamePlural: vscode.l10n.t('Healthcare solutions (Preview)'),
    },
    'Homeone': {
        displayName: vscode.l10n.t('Homeone'),
        displayNamePlural: vscode.l10n.t('Homeones'),
        iconInformation: { fileName: 'pipeline_24.svg', isThemed: true },
        portalFolder: 'homeones',
    },
    'KustoDashboard': {
        displayName: vscode.l10n.t('Real-Time Dashboard'),
        displayNamePlural: vscode.l10n.t('Dashboards'),
        iconInformation: { fileName: 'real_time_dashboard_24.svg', isThemed: true },
        portalFolder: 'kustodashboards',
    },
    'KustoEventHubDataConnection': {
        displayName: vscode.l10n.t('Real-Time Analytics Data stream'),
        displayNamePlural: vscode.l10n.t('Real-Time Analytics Data streams'),
    },
    'MicroBatchPipeline': {
        displayName: vscode.l10n.t('Change Data Capture'),
        displayNamePlural: vscode.l10n.t('Change Data Captures'),
        iconInformation: { fileName: 'pipeline_24.svg', isThemed: true },
        portalFolder: 'microbatchpipelines',
    },
    'SQLDbNative': {
        displayName: vscode.l10n.t('SQL Database'),
        displayNamePlural: vscode.l10n.t('SQL Databases'),
        iconInformation: { fileName: 'sql_database_24.svg', isThemed: true },
        portalFolder: 'sqldatabases',
    },
    'TestArtifact': {
        displayName: 'Test Artifact',
        displayNamePlural: 'test artifacts',
        iconInformation: { fileName: 'notebook_24.svg', isThemed: true },
    },
    'WebApiService': {
        displayName: vscode.l10n.t('WebApiService'),
        displayNamePlural: vscode.l10n.t('WebApiServices'),
        iconInformation: { fileName: 'sql_database_24.svg', isThemed: true },
    },

    'KustoEventHouse': {
        displayName: vscode.l10n.t('Event House'),
        displayNamePlural: vscode.l10n.t('Event Houses'),
        portalFolder: 'eventhouses',
    },
    'MicrosoftSupplyChainCenter': {
        displayName: vscode.l10n.t('Supply Chain Center'),
        displayNamePlural: vscode.l10n.t('Supply Chain Centers'),
    },
    'monitorMounting': {
        displayName: vscode.l10n.t('Monitor mounting'),
        displayNamePlural: vscode.l10n.t('Mirrored databases'),
    },
    'PgSQLDbNative': {
        displayName: vscode.l10n.t('PostgreSQL Database'),
        displayNamePlural: vscode.l10n.t('PostgreSQL Databases'),
    },
    'SustainabilityDataManager': {
        displayName: vscode.l10n.t('Sustainability Data Manager (Preview)'),
        displayNamePlural: vscode.l10n.t('Sustainability Data Managers'),
    },

    /* eslint-enable @typescript-eslint/naming-convention*/
};
